<input type="hidden" name="po_gb" value="<?=$po_gb?>">
<input type="hidden" name="po_cd" value="<?=$po_cd?>">

<table width='<?=$cf_table_wd_large?>' border="0" cellspacing="0" cellpadding="1" >
  <tr>
    <td class="table_line">
	  <table width="<?=$cf_table_wd_small?>" border="0" cellspacing="1" cellpadding="3">
	  	<tr>
		  <td class="table_menu" colspan="5" align="center">SMS 등록</td>
		  </td>
		</tr>		
		<tr>		  
		  <td class="table_body_text">

			<table cellpadding="0" cellspacing="0" align="center" border="0" bordercolor="#a6c6e0">
				<tr>				
				<td class="g_view" width="100%">						
				  <table width="129" border="0" cellspacing="0" cellpadding="0">
					<tr>
					  <td align="left" valign="top"><img src="/images/sms/quick_top01.gif" width="129" height="52"></td>
					</tr>

					<tr>
					  <td align="center" valign="top" background="/images/sms/quick_top04.gif"><table width="100%" border="0" cellspacing="0" cellpadding="0">
						  <tr>
							<td align="center"><table width="108" height="100%" border="0" cellpadding="0" cellspacing="0">
								<tr>
								  <td height="23"><img src="/images/sms/quick_top02.gif" width="108" height="23"></td>
								</tr>
								<tr>
								  <td height="120" align="center" valign="middle" background="/images/sms/quick_topbg.gif"><table width="85%" height="110" border="0" cellpadding="0" cellspacing="0">
									  <tr>
										<td width="116" align="left" valign="top" style="padding: 2px 2px 2px 2px"><textarea name="fr_msg1" id="fr_msg1" cols="11" rows="8" style="border:0;overflow:hidden" onKeyUp="b_value1();" ></textarea></td>
									  </tr>
									  <tr>
										<td id="byte_v1" height="10" align="right" valign="bottom">0/80Byte </td>
									  </tr>
									</table></td>
								</tr>
								<tr>
								  <td height="7"><img src="/images/sms/quick_top03.gif" width="108" height="7"></td>
								</tr>
							  </table></td>
						  </tr>
						  <tr>
							<td height="6" align="center"></td>
						 </tr>
						  <tr>
							<td height="35" align="center" valign="bottom">
							
							  <!-- <img src="/images/sms/quick_top05_bt.gif" width="108" height="29" border="0" style="cursor:hand" onClick="sms_sendit();"> -->
							  <!-- <input type="reset" value="저 장" class="input_button" width="108" height="29"> -->
							  주문접수
							
							</td>
						  </tr>
						</table></td>
					</tr>
					<tr>
					  <td><img src="/images/sms/quick_top06.gif" width="129" height="11"></td>
					</tr>						
					</table>						
				</td>
				</tr>
			</table>

		  </td>

		  <td class="table_body_text">

			<table cellpadding="0" cellspacing="0" align="center" border="0" bordercolor="#a6c6e0">
				<tr>				
				<td class="g_view" width="100%">						
				  <table width="129" border="0" cellspacing="0" cellpadding="0">
					<tr>
					  <td align="left" valign="top"><img src="/images/sms/quick_top01.gif" width="129" height="52"></td>
					</tr>

					<tr>
					  <td align="center" valign="top" background="/images/sms/quick_top04.gif"><table width="100%" border="0" cellspacing="0" cellpadding="0">
						  <tr>
							<td align="center"><table width="108" height="100%" border="0" cellpadding="0" cellspacing="0">
								<tr>
								  <td height="23"><img src="/images/sms/quick_top02.gif" width="108" height="23"></td>
								</tr>
								<tr>
								  <td height="120" align="center" valign="middle" background="/images/sms/quick_topbg.gif"><table width="85%" height="110" border="0" cellpadding="0" cellspacing="0">
									  <tr>
										<td width="116" align="left" valign="top" style="padding: 2px 2px 2px 2px"><textarea name="fr_msg2" id="fr_msg2" cols="11" rows="8" style="border:0;overflow:hidden" onKeyUp="b_value2();" ></textarea></td>
									  </tr>
									  <tr>
										<td id="byte_v2" height="10" align="right" valign="bottom">0/80Byte </td>
									  </tr>
									</table></td>
								</tr>
								<tr>
								  <td height="7"><img src="/images/sms/quick_top03.gif" width="108" height="7"></td>
								</tr>
							  </table></td>
						  </tr>
						  <tr>
							<td height="6" align="center"></td>
						 </tr>
						  <tr>
							<td height="35" align="center" valign="bottom">
							  입금확인							
							</td>
						  </tr>
						</table></td>
					</tr>
					<tr>
					  <td><img src="/images/sms/quick_top06.gif" width="129" height="11"></td>
					</tr>						
					</table>						
				</td>
				</tr>
			</table>

		  </td>

		  <td class="table_body_text">

			<table cellpadding="0" cellspacing="0" align="center" border="0" bordercolor="#a6c6e0">
				<tr>				
				<td class="g_view" width="100%">						
				  <table width="129" border="0" cellspacing="0" cellpadding="0">
					<tr>
					  <td align="left" valign="top"><img src="/images/sms/quick_top01.gif" width="129" height="52"></td>
					</tr>

					<tr>
					  <td align="center" valign="top" background="/images/sms/quick_top04.gif"><table width="100%" border="0" cellspacing="0" cellpadding="0">
						  <tr>
							<td align="center"><table width="108" height="100%" border="0" cellpadding="0" cellspacing="0">
								<tr>
								  <td height="23"><img src="/images/sms/quick_top02.gif" width="108" height="23"></td>
								</tr>
								<tr>
								  <td height="120" align="center" valign="middle" background="/images/sms/quick_topbg.gif"><table width="85%" height="110" border="0" cellpadding="0" cellspacing="0">
									  <tr>
										<td width="116" align="left" valign="top" style="padding: 2px 2px 2px 2px"><textarea name="fr_msg3" id="fr_msg3" cols="11" rows="8" style="border:0;overflow:hidden" onKeyUp="b_value3();" ></textarea></td>
									  </tr>
									  <tr>
										<td id="byte_v3" height="10" align="right" valign="bottom">0/80Byte </td>
									  </tr>
									</table></td>
								</tr>
								<tr>
								  <td height="7"><img src="/images/sms/quick_top03.gif" width="108" height="7"></td>
								</tr>
							  </table></td>
						  </tr>
						  <tr>
							<td height="6" align="center"></td>
						 </tr>
						  <tr>
							<td height="35" align="center" valign="bottom">
							  배송준비
							</td>
						  </tr>
						</table></td>
					</tr>
					<tr>
					  <td><img src="/images/sms/quick_top06.gif" width="129" height="11"></td>
					</tr>						
					</table>						
				</td>
				</tr>
			</table>

		  </td>

		  <td class="table_body_text">

			<table cellpadding="0" cellspacing="0" align="center" border="0" bordercolor="#a6c6e0">
				<tr>				
				<td class="g_view" width="100%">						
				  <table width="129" border="0" cellspacing="0" cellpadding="0">
					<tr>
					  <td align="left" valign="top"><img src="/images/sms/quick_top01.gif" width="129" height="52"></td>
					</tr>

					<tr>
					  <td align="center" valign="top" background="/images/sms/quick_top04.gif"><table width="100%" border="0" cellspacing="0" cellpadding="0">
						  <tr>
							<td align="center"><table width="108" height="100%" border="0" cellpadding="0" cellspacing="0">
								<tr>
								  <td height="23"><img src="/images/sms/quick_top02.gif" width="108" height="23"></td>
								</tr>
								<tr>
								  <td height="120" align="center" valign="middle" background="/images/sms/quick_topbg.gif"><table width="85%" height="110" border="0" cellpadding="0" cellspacing="0">
									  <tr>
										<td width="116" align="left" valign="top" style="padding: 2px 2px 2px 2px"><textarea name="fr_msg4" id="fr_msg4" cols="11" rows="8" style="border:0;overflow:hidden" onKeyUp="b_value4();" ></textarea></td>
									  </tr>
									  <tr>
										<td id="byte_v4" height="10" align="right" valign="bottom">0/80Byte </td>
									  </tr>
									</table></td>
								</tr>
								<tr>
								  <td height="7"><img src="/images/sms/quick_top03.gif" width="108" height="7"></td>
								</tr>
							  </table></td>
						  </tr>
						  <tr>
							<td height="6" align="center"></td>
						 </tr>
						  <tr>
							<td height="35" align="center" valign="bottom">
							
							  <!-- <img src="/images/sms/quick_top05_bt.gif" width="108" height="29" border="0" style="cursor:hand" onClick="sms_sendit();"> -->
							  <!-- <input type="reset" value="저 장" class="input_button" width="108" height="29"> -->
							  상품발송
							
							</td>
						  </tr>
						</table></td>
					</tr>
					<tr>
					  <td><img src="/images/sms/quick_top06.gif" width="129" height="11"></td>
					</tr>						
					</table>						
				</td>
				</tr>
			</table>

		  </td>

		  <td class="table_body_text">

			<table cellpadding="0" cellspacing="0" align="center" border="0" bordercolor="#a6c6e0">
				<tr>				
				<td class="g_view" width="100%">						
				  <table width="129" border="0" cellspacing="0" cellpadding="0">
					<tr>
					  <td align="left" valign="top"><img src="/images/sms/quick_top01.gif" width="129" height="52"></td>
					</tr>

					<tr>
					  <td align="center" valign="top" background="/images/sms/quick_top04.gif"><table width="100%" border="0" cellspacing="0" cellpadding="0">
						  <tr>
							<td align="center"><table width="108" height="100%" border="0" cellpadding="0" cellspacing="0">
								<tr>
								  <td height="23"><img src="/images/sms/quick_top02.gif" width="108" height="23"></td>
								</tr>
								<tr>
								  <td height="120" align="center" valign="middle" background="/images/sms/quick_topbg.gif"><table width="85%" height="110" border="0" cellpadding="0" cellspacing="0">
									  <tr>
										<td width="116" align="left" valign="top" style="padding: 2px 2px 2px 2px"><textarea name="fr_msg5" id="fr_msg5" cols="11" rows="8" style="border:0;overflow:hidden" onKeyUp="b_value5();" ></textarea></td>
									  </tr>
									  <tr>
										<td id="byte_v5" height="10" align="right" valign="bottom">0/80Byte </td>
									  </tr>
									</table></td>
								</tr>
								<tr>
								  <td height="7"><img src="/images/sms/quick_top03.gif" width="108" height="7"></td>
								</tr>
							  </table></td>
						  </tr>
						  <tr>
							<td height="6" align="center"></td>
						 </tr>
						  <tr>
							<td height="35" align="center" valign="bottom">
							
							  <!-- <img src="/images/sms/quick_top05_bt.gif" width="108" height="29" border="0" style="cursor:hand" onClick="sms_sendit();"> -->
							  <!-- <input type="reset" value="저 장" class="input_button" width="108" height="29"> -->
							  거래완료
							
							</td>
						  </tr>
						</table></td>
					</tr>
					<tr>
					  <td><img src="/images/sms/quick_top06.gif" width="129" height="11"></td>
					</tr>						
					</table>						
				</td>
				</tr>
			</table>

		  </td>

	    </tr>

		<tr>		  
		  <td class="table_body_text">

			<table cellpadding="0" cellspacing="0" align="center" border="0" bordercolor="#a6c6e0">
				<tr>				
				<td class="g_view" width="100%">						
				  <table width="129" border="0" cellspacing="0" cellpadding="0">
					<tr>
					  <td align="left" valign="top"><img src="/images/sms/quick_top01.gif" width="129" height="52"></td>
					</tr>

					<tr>
					  <td align="center" valign="top" background="/images/sms/quick_top04.gif"><table width="100%" border="0" cellspacing="0" cellpadding="0">
						  <tr>
							<td align="center"><table width="108" height="100%" border="0" cellpadding="0" cellspacing="0">
								<tr>
								  <td height="23"><img src="/images/sms/quick_top02.gif" width="108" height="23"></td>
								</tr>
								<tr>
								  <td height="120" align="center" valign="middle" background="/images/sms/quick_topbg.gif"><table width="85%" height="110" border="0" cellpadding="0" cellspacing="0">
									  <tr>
										<td width="116" align="left" valign="top" style="padding: 2px 2px 2px 2px"><textarea name="fr_msg6" id="fr_msg6" cols="11" rows="8" style="border:0;overflow:hidden" onKeyUp="b_value6();" ></textarea></td>
									  </tr>
									  <tr>
										<td id="byte_v6" height="10" align="right" valign="bottom">0/80Byte </td>
									  </tr>
									</table></td>
								</tr>
								<tr>
								  <td height="7"><img src="/images/sms/quick_top03.gif" width="108" height="7"></td>
								</tr>
							  </table></td>
						  </tr>
						  <tr>
							<td height="6" align="center"></td>
						 </tr>
						  <tr>
							<td height="35" align="center" valign="bottom">
							  주문취소
							</td>
						  </tr>
						</table></td>
					</tr>
					<tr>
					  <td><img src="/images/sms/quick_top06.gif" width="129" height="11"></td>
					</tr>						
					</table>						
				</td>
				</tr>
			</table>

		  </td>

		  <td class="table_body_text">

			<table cellpadding="0" cellspacing="0" align="center" border="0" bordercolor="#a6c6e0">
				<tr>				
				<td class="g_view" width="100%">						
				  <table width="129" border="0" cellspacing="0" cellpadding="0">
					<tr>
					  <td align="left" valign="top"><img src="/images/sms/quick_top01.gif" width="129" height="52"></td>
					</tr>

					<tr>
					  <td align="center" valign="top" background="/images/sms/quick_top04.gif"><table width="100%" border="0" cellspacing="0" cellpadding="0">
						  <tr>
							<td align="center"><table width="108" height="100%" border="0" cellpadding="0" cellspacing="0">
								<tr>
								  <td height="23"><img src="/images/sms/quick_top02.gif" width="108" height="23"></td>
								</tr>
								<tr>
								  <td height="120" align="center" valign="middle" background="/images/sms/quick_topbg.gif"><table width="85%" height="110" border="0" cellpadding="0" cellspacing="0">
									  <tr>
										<td width="116" align="left" valign="top" style="padding: 2px 2px 2px 2px"><textarea name="fr_msg7" id="fr_msg7" cols="11" rows="8" style="border:0;overflow:hidden" onKeyUp="b_value7();" ></textarea></td>
									  </tr>
									  <tr>
										<td id="byte_v7" height="10" align="right" valign="bottom">0/80Byte </td>
									  </tr>
									</table></td>
								</tr>
								<tr>
								  <td height="7"><img src="/images/sms/quick_top03.gif" width="108" height="7"></td>
								</tr>
							  </table></td>
						  </tr>
						  <tr>
							<td height="6" align="center"></td>
						 </tr>
						  <tr>
							<td height="35" align="center" valign="bottom">
							  환불요청
							</td>
						  </tr>
						</table></td>
					</tr>
					<tr>
					  <td><img src="/images/sms/quick_top06.gif" width="129" height="11"></td>
					</tr>						
					</table>						
				</td>
				</tr>
			</table>

		  </td>

		  <td class="table_body_text">

			<table cellpadding="0" cellspacing="0" align="center" border="0" bordercolor="#a6c6e0">
				<tr>				
				<td class="g_view" width="100%">						
				  <table width="129" border="0" cellspacing="0" cellpadding="0">
					<tr>
					  <td align="left" valign="top"><img src="/images/sms/quick_top01.gif" width="129" height="52"></td>
					</tr>

					<tr>
					  <td align="center" valign="top" background="/images/sms/quick_top04.gif"><table width="100%" border="0" cellspacing="0" cellpadding="0">
						  <tr>
							<td align="center"><table width="108" height="100%" border="0" cellpadding="0" cellspacing="0">
								<tr>
								  <td height="23"><img src="/images/sms/quick_top02.gif" width="108" height="23"></td>
								</tr>
								<tr>
								  <td height="120" align="center" valign="middle" background="/images/sms/quick_topbg.gif"><table width="85%" height="110" border="0" cellpadding="0" cellspacing="0">
									  <tr>
										<td width="116" align="left" valign="top" style="padding: 2px 2px 2px 2px"><textarea name="fr_msg8" id="fr_msg8" cols="11" rows="8" style="border:0;overflow:hidden" onKeyUp="b_value8();" ></textarea></td>
									  </tr>
									  <tr>
										<td id="byte_v8" height="10" align="right" valign="bottom">0/80Byte </td>
									  </tr>
									</table></td>
								</tr>
								<tr>
								  <td height="7"><img src="/images/sms/quick_top03.gif" width="108" height="7"></td>
								</tr>
							  </table></td>
						  </tr>
						  <tr>
							<td height="6" align="center"></td>
						 </tr>
						  <tr>
							<td height="35" align="center" valign="bottom">
							  환불완료
							</td>
						  </tr>
						</table></td>
					</tr>
					<tr>
					  <td><img src="/images/sms/quick_top06.gif" width="129" height="11"></td>
					</tr>						
					</table>						
				</td>
				</tr>
			</table>

		  </td>

		  <td class="table_body_text">

			<table cellpadding="0" cellspacing="0" align="center" border="0" bordercolor="#a6c6e0">
				<tr>				
				<td class="g_view" width="100%">						
				  <table width="129" border="0" cellspacing="0" cellpadding="0">
					<tr>
					  <td align="left" valign="top"><img src="/images/sms/quick_top01.gif" width="129" height="52"></td>
					</tr>

					<tr>
					  <td align="center" valign="top" background="/images/sms/quick_top04.gif"><table width="100%" border="0" cellspacing="0" cellpadding="0">
						  <tr>
							<td align="center"><table width="108" height="100%" border="0" cellpadding="0" cellspacing="0">
								<tr>
								  <td height="23"><img src="/images/sms/quick_top02.gif" width="108" height="23"></td>
								</tr>
								<tr>
								  <td height="120" align="center" valign="middle" background="/images/sms/quick_topbg.gif"><table width="85%" height="110" border="0" cellpadding="0" cellspacing="0">
									  <tr>
										<td width="116" align="left" valign="top" style="padding: 2px 2px 2px 2px"><textarea name="fr_msg9" id="fr_msg9" cols="11" rows="8" style="border:0;overflow:hidden" onKeyUp="b_value9();" ></textarea></td>
									  </tr>
									  <tr>
										<td id="byte_v9" height="10" align="right" valign="bottom">0/80Byte </td>
									  </tr>
									</table></td>
								</tr>
								<tr>
								  <td height="7"><img src="/images/sms/quick_top03.gif" width="108" height="7"></td>
								</tr>
							  </table></td>
						  </tr>
						  <tr>
							<td height="6" align="center"></td>
						 </tr>
						  <tr>
							<td height="35" align="center" valign="bottom">
							  교환요청
							</td>
						  </tr>
						</table></td>
					</tr>
					<tr>
					  <td><img src="/images/sms/quick_top06.gif" width="129" height="11"></td>
					</tr>						
					</table>						
				</td>
				</tr>
			</table>

		  </td>

		  <td class="table_body_text">

			<table cellpadding="0" cellspacing="0" align="center" border="0" bordercolor="#a6c6e0">
				<tr>				
				<td class="g_view" width="100%">						
				  <table width="129" border="0" cellspacing="0" cellpadding="0">
					<tr>
					  <td align="left" valign="top"><img src="/images/sms/quick_top01.gif" width="129" height="52"></td>
					</tr>

					<tr>
					  <td align="center" valign="top" background="/images/sms/quick_top04.gif"><table width="100%" border="0" cellspacing="0" cellpadding="0">
						  <tr>
							<td align="center"><table width="108" height="100%" border="0" cellpadding="0" cellspacing="0">
								<tr>
								  <td height="23"><img src="/images/sms/quick_top02.gif" width="108" height="23"></td>
								</tr>
								<tr>
								  <td height="120" align="center" valign="middle" background="/images/sms/quick_topbg.gif"><table width="85%" height="110" border="0" cellpadding="0" cellspacing="0">
									  <tr>
										<td width="116" align="left" valign="top" style="padding: 2px 2px 2px 2px"><textarea name="fr_msg10" id="fr_msg10" cols="11" rows="8" style="border:0;overflow:hidden" onKeyUp="b_value10();" ></textarea></td>
									  </tr>
									  <tr>
										<td id="byte_v10" height="10" align="right" valign="bottom">0/80Byte </td>
									  </tr>
									</table></td>
								</tr>
								<tr>
								  <td height="7"><img src="/images/sms/quick_top03.gif" width="108" height="7"></td>
								</tr>
							  </table></td>
						  </tr>
						  <tr>
							<td height="6" align="center"></td>
						 </tr>
						  <tr>
							<td height="35" align="center" valign="bottom">
							  교환완료
							</td>
						  </tr>
						</table></td>
					</tr>
					<tr>
					  <td><img src="/images/sms/quick_top06.gif" width="129" height="11"></td>
					</tr>						
					</table>						
				</td>
				</tr>
			</table>

		  </td>

	    </tr>
	  </table>
	</td>
  </tr>
</table>

<br>

<table width='<?=$cf_table_wd_large?>' border="0" cellspacing="0" cellpadding="1" >
  <tr>
    <td class="table_line">
	  <table width="<?=$cf_table_wd_small?>" border="0" cellspacing="1" cellpadding="3">
	    <tr>
		  <td align="center" colspan="2" bgColor="#D7E3EC">
			<font size=2 color=#000066>			
			<input type="button" value="SMS등록" onClick="checkIt(this.form)" class="input_button">			
			</font>
		  </td>
	    </tr>
	  </table>
    </td>
  </tr>
</table>
