<div id="bnnrslidewrap">
				<div class="bnnrslide">
					<ul class="rolling-list">
											<li class="rolling-bnnr"><a href="http://www.bu.ac.kr/main_index.jsp" target="_blank" title="새창링크"><img src="/images/foot_banner1.gif" alt="백석대학교" /></a></li>
											<li class="rolling-bnnr"><a href="http://www.bscu.ac.kr/index.jsp" target="_blank" title="새창링크"><img src="/images/foot_banner2.gif" alt="백석문화대학교" /></a></li>
											<li class="rolling-bnnr"><a href="http://www.mest.go.kr/main.do" target="_blank" title="새창링크"><img src="/images/foot_banner3.gif" alt="교육과학기술부" /></a></li>
											<li class="rolling-bnnr"><a href="https://www.kedi.re.kr/khome/main/webhome/Home.do" target="_blank" title="새창링크"><img src="/images/foot_banner4.gif" alt="한국교육개발원" /></a></li>
											<li class="rolling-bnnr"><a href="http://ncle.kedi.re.kr/" target="_blank" title="새창링크"><img src="/images/foot_banner5.gif" alt="평생교육진흥원" /></a></li>
											<li class="rolling-bnnr"><a href="http://chungnam.lll.or.kr/html/main/local_main.php" target="_blank" title="새창링크"><img src="/images/foot_banner6.gif" alt="충남평생교육정보센터" /></a></li>
											<li class="rolling-bnnr"><a href="https://www.cle.or.kr/new/main/main.html" target="_blank" title="새창링크"><img src="/images/foot_banner7.gif" alt="충청남도평생교육원" /></a></li>
											<li class="rolling-bnnr"><a href="http://lib.bu.ac.kr/" target="_blank" title="새창링크"><img src="/images/foot_banner8.gif" alt="백석학술정보관" /></a></li>
											<li class="rolling-bnnr"><a href="http://cnile.or.kr/" target="_blank" title="새창링크"><img src="/images/foot_banner9.gif" alt="충청남도평생교육진흥원" /></a></li>

											
								</ul>
							</div>
				<p class="btndir">
					<button class="rolling-btnl"><img src="/images/foot_ban_prev.gif" alt="이전" /></button>
					<button class="rolling-btnr"><img src="/images/foot_ban_next.gif" alt="다음" /></button>
				</p>
			</div>
<script type="text/javascript">var bnnrslide = new bnnrslide("bnnrslidewrap")</script>