

                </div><!-- contents END -->

            </div><!-- //컨텐츠contents_wrap -->
     
        </div><!--// wrap_sub end -->
    </div><!--// wrap end -->
 

 <div style="clear:both;width:100%;height:10px;"></div>
<!-- footer start -->

	<div id="footer">	
		<div class="foot">			
			<p class="logo"><img src="/images/f_logo.gif" alt="종로세종당구아카데미 국일관당구클럽" /></p>				
			<div class="footmenu">
				<a href="/greeting.html?sm=1_1">시설소개</a>&nbsp;&nbsp; | &nbsp;&nbsp;
				<a href="/course.html?sm=2_1">수강안내 및 수강료</a>	&nbsp;&nbsp; | &nbsp;&nbsp;
				<a href="/common/board/list.html?a_gb=board&a_cd=2&a_item=0&sm=3_1">아카데미 소식</a>	&nbsp;&nbsp; | &nbsp;&nbsp;
				<a href="/location.html?sm=4_1">찾아오시는 길</a>
			</div>
			<div class="address">			
				<address>
 				 주소 : 서울 종로구 관수동 20번지 국일관드림펠리스 6F&nbsp;&nbsp;  전화 : 02-2279-0074 / 070-8883-1273&nbsp;&nbsp;  팩스 : 02-2277-1273&nbsp;&nbsp;  사업자등록번호 215-87-84938<br />
				</address>					
				<p>Copyright © 2014 종로세종당구아카데미. All rights reserved. </p>		
			</div>  
			
		</div>	
	</div>


<!--// footer end -->

 
 
</div><!--// wrapper end -->


</body>
</html>