<!-- footer start -->
 <?if(substr($sm,0,1)!="6"){?>
	<div id="footer">	
		<div class="foot">			
			<p class="logo"><img src="/images/f_logo.jpg" alt="피치텍" /></p>				
			<div class="footmenu">
				<a href="/contents/company.html?sm=1_1">회사소개</a>&nbsp;&nbsp; | &nbsp;&nbsp;
				<a href="/contents/raw.html?sm=7_4">이용약관</a>&nbsp;&nbsp; | &nbsp;&nbsp;
				<a href="/contents/privacy.html?sm=7_5">개인정보취급방침</a>&nbsp;&nbsp; | &nbsp;&nbsp;
				<a href="/contents/email.html?sm=7_6">이메일주소무단수집거부</a>	&nbsp;&nbsp; | &nbsp;&nbsp;		
				<a href="/contents/location.html?sm=1_5">오시는 길</a>			
			</div>
			<div class="address">			
				<address><!--상호 : 주식회사 피치텍&nbsp;&nbsp;   대표자 : 박해성&nbsp;&nbsp;    사업자등록번호 : 113-85-37514 &nbsp;&nbsp;  통신판매업신고번호 : 제2014-서울 구로-0527호<br />
				[직영점]  주소 : 152-790 서울특별시 구로구 디지털로 306, 604(구로동 182-13 대륭포스트타워2차) &nbsp;&nbsp; 전화 : 02-859-3477 &nbsp;&nbsp; 팩스 : 02-859-3478 -->
 				상호 : 주식회사 피치텍&nbsp;&nbsp;   대표자 : 박해성&nbsp;&nbsp;    사업자등록번호 : 113-86-59719  <br />
				[본 &nbsp;&nbsp;사]  주소 : 152-790 서울특별시 구로구 디지털로 306, 604(구로동 182-13 대륭포스트타워2차) &nbsp;&nbsp; 전화 : 02-859-3477 &nbsp;&nbsp; 팩스 : 02-859-3478<br />
			상호 : 주식회사 피치텍&nbsp;&nbsp;  대표자 : 박해성&nbsp;&nbsp;  사업자등록번호 : 113-85-37514&nbsp;&nbsp;  통신판매업신고번호 : 제2014-서울 구로-0527호 <br />
				[직영점] 주소 : 152-873 서울특별시 구로구 도림로 47-1, 201(구로동 769-267 2층)&nbsp;&nbsp;  전화 : 02-6205-3477&nbsp;&nbsp;  팩스 : 02-6205-3478<br />
				</address>					
				<p>Copyright © 2014 PeachTech. All rights reserved. </p>		
			</div>  
			<div class="escrow"><img src='http://image.inicis.com/mkt/certmark/escrow/escrow_74x74_color.png' border="0" alt="클릭하시면 이니시스 결제시스템의 유효성을 확인하실 수 있습니다." style="cursor:hand" Onclick=javascript:window.open("https://mark.inicis.com/mark/escrow_popup.php?no=55398&st=1400563268","mark","scrollbars=no,resizable=no,width=565,height=683");></div>
		</div>	
	</div>
<?}else{?>
	<div id="footer">	
		<div class="foot">			
			<p class="logo"><img src="/images/f_logo.jpg" alt="피치텍" /></p>				
			<div class="footmenu">
				<a href="/contents/company.html?sm=1_1">회사소개</a>&nbsp;&nbsp; | &nbsp;&nbsp;
				<a href="/contents/raw.html?sm=7_4">이용약관</a>&nbsp;&nbsp; | &nbsp;&nbsp;
				<a href="/contents/privacy.html?sm=7_5">개인정보취급방침</a>&nbsp;&nbsp; | &nbsp;&nbsp;
				<a href="/contents/email.html?sm=7_6">이메일주소무단수집거부</a>	&nbsp;&nbsp; | &nbsp;&nbsp;		
				<a href="/contents/location.html?sm=1_5">오시는 길</a>			
			</div>
			<div class="address">			
				<address>
				<!--상호 : 주식회사 피치텍&nbsp;&nbsp;   대표자 : 박해성&nbsp;&nbsp;    사업자등록번호 :  113-85-37514 &nbsp;&nbsp;  통신판매업신고번호 : 제2014-서울 구로-0527호<br />
				[직영점]  주소 : 152-790 서울특별시 구로구 디지털로 306, 604(구로동 182-13 대륭포스트타워2차) &nbsp;&nbsp; 전화 : 02-859-3477 &nbsp;&nbsp; 팩스 : 02-859-3478-->	
 				상호 : 주식회사 피치텍&nbsp;&nbsp;   대표자 : 박해성&nbsp;&nbsp;    사업자등록번호 : 113-86-59719  <br />
				[본 &nbsp;&nbsp;사]  주소 : 152-790 서울특별시 구로구 디지털로 306, 604(구로동 182-13 대륭포스트타워2차) &nbsp;&nbsp; 전화 : 02-859-3477 &nbsp;&nbsp; 팩스 : 02-859-3478<br />
			상호 : 주식회사 피치텍&nbsp;&nbsp;  대표자 : 박해성&nbsp;&nbsp;  사업자등록번호 : 113-85-37514&nbsp;&nbsp;  통신판매업신고번호 : 제2014-서울 구로-0527호 <br />
				[직영점] 주소 : 152-873 서울특별시 구로구 도림로 47-1, 201(구로동 769-267 2층)&nbsp;&nbsp;  전화 : 02-6205-3477&nbsp;&nbsp;  팩스 : 02-6205-3478<br /> 
				</address>					
				<p>Copyright © 2014 PeachTech. All rights reserved. </p>				
			</div> 
			<div class="escrow"><img src='http://image.inicis.com/mkt/certmark/escrow/escrow_74x74_color.png' border="0" alt="클릭하시면 이니시스 결제시스템의 유효성을 확인하실 수 있습니다." style="cursor:hand" Onclick=javascript:window.open("https://mark.inicis.com/mark/escrow_popup.php?no=55398&st=1400563268","mark","scrollbars=no,resizable=no,width=565,height=683");></div>	
		</div>	
	</div>
<?}?>

<!--// footer end -->
