
			  </div>
			  <!--//contents-->

		  </div><!--//컨텐츠-->

		</div>
		<!--//main contents-->
  
  </div>

  <!--footer-->
		<div id="footer">
		   <div class="foot_center">
		        <div class="f_menu">
                   <ul>
						<li><a href="javascript:FlashLink(5,3)"><img src="/en/images/f_menu01.gif"></a></li>
						<li><a href="javascript:FlashLink(5,4)"><img src="/en/images/f_menu02.gif"></a></li>
						<li><a href="/main.html"><img src="/en/images/f_menu03.gif"></a></li>
						<li><img src="/en/images/f_menu04.gif"></li>
					</ul>
				</div>
				<div class="foot_logo"><img src="/en/images/f_logo.gif" alt="if-imagination factory" /></div>
				<div class="foot">  
					
					<address>
						<img src="/en/images/copyright.gif" alt="서울특별시 중구 동호로24길 27-10호 매표화학">
					</address> 
				</div>
				
			</div>
		</div>
      <!--//footer-->

</div>

</body>
</html>