            <div id="leftcolumn">
                    <div id="snbwrap">
                    <h3><img src="/images/left5.gif" alt="사이트맵" /></h3>
                    <ul id="snb">
                        <li class="menus"><a class="menus-title" id="lm1" href="/sitemap.html?sm=4_1">사이트맵</a></li>
                    </ul>
                </div>
                <script type="text/javascript">snbMenu("snbwrap","<?=$tm_submenu_num?>");</script>                  
            <a href="/course.html?sm=2_1"><img src="/images/left_banner.gif" alt="" /></a><br />
            </div>