<div id="leftcolumn">
	<div id="snbwrap">
		<h3><img src="/images/left1.gif" alt="인사말" /></h3>
		<ul id="snb">
			<li class="menus"><a class="menus-title" id="lm1" href="/greeting.html?sm=1_1">인사말씀</a></li>
			<li class="menus"><a class="menus-title" id="lm2" href="/company.html?sm=1_2">시설소개</a></li>
		</ul>
	</div>
	<script type="text/javascript">snbMenu("snbwrap","<?=$tm_submenu_num?>");</script>
	<a href="/course.html?sm=2_1"><img src="/images/left_banner.gif" alt="" /></a>
	<br />
</div>