<div id="leftcolumn">
	<div id="snbwrap">
		<h3><img src="/images/left3.gif" alt="커뮤니티" /></h3>
		<ul id="snb">
			<li class="menus"><a class="menus-title" id="lm1" href="/common/board/list.html?a_gb=board&a_cd=2&a_item=0&sm=3_1">아카데미소식</a></li>
			<li class="menus"><a class="menus-title" id="lm2" href="/common/board/list.html?a_gb=board&a_cd=1&a_item=0&sm=3_2">동호회소식</a></li>
			<li class="menus"><a class="menus-title" id="lm3" href="/common/board/list.html?a_gb=board&a_cd=3&a_item=0&sm=3_3">자유게시판</a></li>			
		</ul>
	</div>
	<script type="text/javascript">snbMenu("snbwrap","<?=$tm_submenu_num?>");</script>
	<a href="/course.html?sm=2_1"><img src="/images/left_banner.gif" alt="" /></a>
	<br />
</div>