<div id="leftcolumn">
	<div id="snbwrap">
		<h3><img src="/images/left4.gif" alt="찾아오시는길" /></h3>
		<ul id="snb">
			<li class="menus"><a class="menus-title" id="lm1" href="/location.html?sm=4_1">찾아오시는길</a></li>
		</ul>
	</div>
	<script type="text/javascript">snbMenu("snbwrap","<?=$tm_submenu_num?>");</script>
	<a href="/course.html?sm=2_1"><img src="/images/left_banner.gif" alt="" /></a>
	<br />
</div>