<div id="leftcolumn">
	<div id="snbwrap">
		<h3><img src="/images/left6.gif" alt="공지사항" /></h3>
		<ul id="snb">
			<li class="menus"><a class="menus-title" id="lm1" href="/common/board/list.html?a_gb=board&a_cd=4&a_item=0&sm=6_1">공지사항</a></li>
		</ul>
	</div>
	<script type="text/javascript">snbMenu("snbwrap","<?=$tm_submenu_num?>");</script>
	<a href="/course.html?sm=2_1"><img src="/images/left_banner.gif" alt="" /></a>
	<br />
</div>