<div id="leftcolumn">
	<div id="snbwrap">
		<h3><img src="/images/left2.gif" alt="강의안내" /></h3>
		<ul id="snb">
			<li class="menus"><a class="menus-title" id="lm1" href="/course.html?sm=2_1">수강안내 및 수강료</a></li>
			<li class="menus"><a class="menus-title" id="lm2" href="/lecturer.html?sm=2_2">강사소개</a></li>
		</ul>
	</div>
	<script type="text/javascript">snbMenu("snbwrap","<?=$tm_submenu_num?>");</script>
	<a href="/course.html?sm=2_1"><img src="/images/left_banner.gif" alt="" /></a>
	<br />
</div>