			<div class="gnb-quick">
				<ul>
					<li><a href="/en/"><img src="/en/images/t_home.jpg" alt="Home" /></a></li>
					<li><a href="/en/contents/sitemap.html?sm=9_1"><img src="/en/images/t_sitemap.jpg" alt="sitemap" /></a></li>
					<li class="pdl6"><a href="/"><img src="/en/images/t_kor.jpg" alt="KOREAN" /></a></li>
					<li class="pdl6"><a href="/en/contents/agent.html?sm=8_1"><img src="/en/images/t_agent.jpg" alt="대리점" /></a></li>
					<li class="pdl6"><a href="http://www.facebook.com/handonghydro" target="_blank"><img src="/en/images/t_fb.jpg" alt="facebook" /></a></li>

				</ul>
			</div>
 
			<div class="gnb">
				<h1 class="logo"><a href="/"><img src="/en/images/logo.jpg" alt="Handong Hydro" /></a></h1>
				<div class="gnbmenu">
					<ul class="topmenu">
						<li><a href="/en/contents/company.html?sm=1_1" onmouseover="menuOver(this)" onmouseout="menuOut(this)"  onfocus="menuOver(this)" onblur="menuOut(this)"><img src="/en/images/m1.jpg" alt="About Us" /></a></li>
						<li><a href="/en/contents/hydro_water.html?sm=2_1" onmouseover="menuOver(this)" onmouseout="menuOut(this)"  onfocus="menuOver(this)" onblur="menuOut(this)"><img src="/en/images/m2.jpg" alt="Hydrogen water story" /></a></li>
						<li><a href="/en/contents/howtouse.html?sm=3_1" onmouseover="menuOver(this)" onmouseout="menuOut(this)"  onfocus="menuOver(this)" onblur="menuOut(this)"><img src="/en/images/m3.jpg" alt="Introduction of products" /></a></li>
						<li><a href="/shopping/shop/list.html?a_gb=shop&a_cd=5&a_item=0&po_it_no=i101&po_no=1&po_it_lclass=i10&sm=4_0" onmouseover="menuOver(this)" onmouseout="menuOut(this)"  onfocus="menuOver(this)" onblur="menuOut(this)"><img src="/en/images/m4.jpg" alt="쇼핑몰" /></a></li>
						<li><a href="/common/board/list.html?a_gb=board&a_cd=1&a_item=0&sm=5_1" onmouseover="menuOver(this)" onmouseout="menuOut(this)"  onfocus="menuOver(this)" onblur="menuOut(this)"><img src="/en/images/m5.jpg" alt="PR center" /></a></li>
						<li class="last"><a href="/common/board/list.html?a_gb=board&a_cd=6&a_item=0&sm=6_1" onmouseover="menuOver(this)" onmouseout="menuOut(this)"  onfocus="menuOver(this)" onblur="menuOut(this)"><img src="/en/images/m6.jpg" alt="Customer center" /></a></li>
					</ul>
				</div>
			</div>


			
			<div class="gnb-sub" style="display:none;">
				<div class="gnbmenu">

					<!-- 1 회사소개 -->
					<ul class="smenu01">
						<li><a class="smenu1" href="/en/contents/company.html?sm=1_1">About Us</a></li>
						<li><a class="smenu2" href="/en/contents/greet.html?sm=1_2">Greetings</a></li>
						<li><a class="smenu3" href="/en/contents/found.html?sm=1_3">Background of establishment</a></li>
						<li><a class="smenu4" href="/en/contents/vision.html?sm=1_4">Vision</a></li>
						<li><a class="smenu5" href="/en/contents/business.html?sm=1_5">Business areas</a></li>
						<li><a class="smenu6" href="/en/contents/location.html?sm=1_6">Location</a></li>
					</ul>

					<!-- 2 수소수이야기 -->
					<ul class="smenu02">
						<li><a class="smenu2" href="/en/contents/hydro_water.html?sm=2_1">Hydrogen water story</a></li>
						<li><a class="smenu4" href="/en/contents/racipe.html?sm=2_2">Hydrogen water recipe</a></li>
						<li><a class="smenu1" href="/common/board/list.html?a_gb=board&a_cd=10&a_item=0&sm=2_3">Hydrogen water information center </a></li>
						<li><a class="smenu6" href="/common/board/listbody.html?a_gb=board&a_cd=11&a_item=0&sm=2_4">Video archives</a></li>
					</ul>

					<!--3 제품소개  -->
					<ul class="smenu03">
						<li><a class="smenu1" href="/en/contents/howtouse.html?sm=3_1">How to use</a></li>
						<li><a class="smenu2" href="/en/contents/hydraction_is.html?sm=3_2">What is Hydraction? </a></li>
						<li><a class="smenu3" href="/en/contents/hydraction_1.html?sm=3_3">HydractionⅠ</a></li>
						<li><a class="smenu4" href="/en/contents/hydraction_2.html?sm=3_4">HydractionⅡ</a></li>
						<li><a class="smenu5" href="/en/contents/h2_mini.html?sm=3_5">H<sub>2</sub>Mini</a></li>
					</ul>

					<!-- 4 쇼핑몰 -->
					<ul class="smenu04">
						<li><a class="smenu1" href="/shopping/shop/listbody.html?a_gb=shop&a_cd=5&a_item=0&sm=4_1&po_it_no=i103&po_no=3&po_it_lclass=i10">하이드랙션Ⅰ</a></li>
						<li><a class="smenu2" href="/shopping/shop/listbody.html?a_gb=shop&a_cd=5&a_item=0&sm=4_2&po_it_no=i101&po_no=1&po_it_lclass=i10">하이드랙션Ⅱ</a></li>
						<li><a class="smenu3" href="/shopping/shop/listbody.html?a_gb=shop&a_cd=5&a_item=0&sm=4_3&po_it_no=4&po_no=4&po_it_lclass=i10"><span style="letter-spacing:-1px;">하이드랙션염소제거기</span></a></li>
						<li><a class="smenu4" href="/shopping/shop/listbody.html?a_gb=shop&a_cd=5&a_item=0&sm=4_4&po_it_no=i102&po_no=2&po_it_lclass=i10">H<sub>2</sub>Mini</a></li>
					</ul>

					<!-- 5 홍보관 -->
					<ul class="smenu05">
						<li><a class="smenu1" href="/common/board/list.html?a_gb=board&a_cd=1&a_item=0&sm=5_1">Notice</a></li>
						<li><a class="smenu2" href="/common/board/list.html?a_gb=board&a_cd=2&a_item=0&sm=5_2">Press release</a></li>
						<li><a class="smenu3" href="/common/board/list.html?a_gb=board&a_cd=3&a_item=0&sm=5_3">News events</a></li>
						<li><a class="smenu4" href="/common/board/list.html?a_gb=board&a_cd=4&a_item=0&sm=5_4">CF data</a></li>
						<li><a class="smenu5" href="/common/board/list.html?a_gb=board&a_cd=5&a_item=0&sm=5_5">Events</a></li>
					</ul>

					<!-- 6 고객센터 -->
					<ul class="smenu06">
						<li><a class="smenu1" href="/common/board/list.html?a_gb=board&a_cd=6&a_item=0&sm=6_1">Customer reviews</a></li>
						<li><a class="smenu2" href="/common/board/list.html?a_gb=board&a_cd=7&a_item=0&sm=6_2">Product FAQ</a></li>
						<li><a class="smenu3" href="/common/board/list.html?a_gb=board&a_cd=8&a_item=0&sm=6_3">Product Q&A</a></li>
					</ul>

				</div>
			</div>