
<table width='<?=$cf_table_wd_large?>' border="0" cellspacing="0" cellpadding="1" >
  <tr>
    <td class="table_line">
	  <table width="<?=$cf_table_wd_small?>" border="0" cellspacing="1" cellpadding="3">
	  	<tr>
		  <td class="table_menu" colspan="4" align="center">상품분류 삭제</td>
		  </td>
		</tr>
		<tr>
		  <td class="table_body_menu">코드<font color=#CC3300> *</font></td>
		  <td class="table_body_text" colspan="3">
		  <?=$my_cd?>
		  </td>
		</tr>
		<tr>
		  <td class="table_body_menu" width="20%" cols>은행명<font color=#CC3300> *</font></td>
		  <td class="table_body_text" colspan="3">
		  <?=$my_nm?>
		  </td>
		</tr>
		<tr>
		  <td class="table_body_menu">예금주</td>
		  <td class="table_body_text" colspan="3">
		  <?=$my_con_cd?></td>
	    </tr>
	    <tr>
		  <td class="table_body_menu">계좌번호</td>
		  <td class="table_body_text" colspan="3">
		  <?=$my_bigo?></td>
	    </tr>
	  </table>
	</td>
  </tr>
</table>

<br>

<table width='<?=$cf_table_wd_large?>' border="0" cellspacing="0" cellpadding="1" >
  <tr>
    <td class="table_line">
	  <table width="<?=$cf_table_wd_small?>" border="0" cellspacing="1" cellpadding="3">
	    <tr>
		  <td align="center" colspan="2" class="table_body_menu">
			<?=$DELETE?> <?=$LIST?>
		  </td>
	    </tr>
	  </table>
    </td>
  </tr>
</table>

