 <table width="<?=$cf_table_wd_large?>" border="0" cellspacing="0" cellpadding="0">
    <tr height='3'>
      <td width="120" bgcolor='#cacaca'></td>
      <td width="480" bgcolor='#444444'></td>
    </tr>
  </table>


<table width="<?=$cf_table_wd_large?>" border="0" cellpadding="0" cellspacing="0">

	<tr bgcolor='#F4F4F4' height="27">
		<th width="119" align="center">사이트 명</th>
		<td width="1"><img src="<?=$cf_images_dir?>/th_line.gif"></td>
        <td width="480">&nbsp;&nbsp;<input type="text" name="fr_site_nm" size="40" maxlength="40" value="<?=$my_site_nm?>" class='box'></td>
    </tr>
    <tr>
	    <td bgcolor='#E4E4E4' height='1' colspan='3'></td>
    </tr>

	<tr bgcolor='#F4F4F4' height="27">
		<th width="119" align="center">전화 번호</th>
		<td width="1"><img src="<?=$cf_images_dir?>/th_line.gif"></td>
        <td width="480">&nbsp;&nbsp;<input type="text" name="fr_site_tel" size="40" maxlength="40" value="<?=$my_site_tel?>" class='box'></td>
    </tr>
    <tr>
	    <td bgcolor='#E4E4E4' height='1' colspan='3'></td>
    </tr>

	<tr bgcolor='#F4F4F4' height="27">
		<th width="119" align="center">사이트 제목 표시줄</th>
		<td width="1"><img src="<?=$cf_images_dir?>/th_line.gif"></td>
        <td width="480">&nbsp;&nbsp;<input type="text" name="fr_meta_title" size="85" maxlength="250" value="<?=$my_meta_title?>" class='box'></td>
    </tr>
    <tr>
	    <td bgcolor='#E4E4E4' height='1' colspan='3'></td>
    </tr>


	<tr bgcolor='#F4F4F4' height="27">
		<th width="119" align="center">사이트 키워드</th>
		<td width="1"><img src="<?=$cf_images_dir?>/th_line.gif"></td>
        <td width="480">&nbsp;&nbsp;<input type="text" name="fr_meta_keywd" size="85" maxlength="250" value="<?=$my_meta_keywd?>" class='box'></td>
    </tr>
    <tr>
	    <td bgcolor='#E4E4E4' height='1' colspan='3'></td>
    </tr>

	<tr bgcolor='#F4F4F4' height="27">
		<th width="119" align="center">사이트 설명</th>
		<td width="1"><img src="<?=$cf_images_dir?>/th_line.gif"></td>
        <td width="480">&nbsp;&nbsp;<input type="text" name="fr_meta_desc" size="85" maxlength="250" value="<?=$my_meta_desc?>" class='box'></td>
    </tr>
    <tr>
	    <td bgcolor='#E4E4E4' height='1' colspan='3'></td>
    </tr>

	<tr bgcolor='#F4F4F4' height="27">
		<th width="119" align="center">관리 이메일</th>
		<td width="1"><img src="<?=$cf_images_dir?>/th_line.gif"></td>
        <td width="480">&nbsp;&nbsp;<input type="text" name="fr_mail_from" size="60" maxlength="250" value="<?=$my_mail_from?>" class='box'></td>
    </tr>
    <tr>
	    <td bgcolor='#E4E4E4' height='1' colspan='3'></td>
    </tr>

	

</table>


  <table width="<?=$cf_table_wd_large?>" border="0" cellspacing="0" cellpadding="0">
    <tr height='1'>
      <td bgcolor='#DBDBDB'></td>
    </tr>
    <tr height='4'>
      <td bgcolor='#F5F5F5'></td>
    </tr>
  </table>
  <br>

  <table width="<?=$cf_table_wd_large?>" border="0" cellspacing="0" cellpadding="0">
    <tr>
      <td height="36" align="right">
	    <input type="image" src="<?=$cf_images_dir?>/ok.gif"></a>
	    <a href="javascript:signform.reset();"><img src="<?=$cf_images_dir?>/cancel.gif" border="0"></a>
	  </td>
    </tr>
  </table>
  <BR>
  <BR>

