
<table width='<?=$cf_table_wd_large?>' border="0" cellspacing="0" cellpadding="1" >
  <tr>
    <td class="table_line">
	  <table width="<?=$cf_table_wd_small?>" border="0" cellspacing="1" cellpadding="3">
	  	<tr>
		  <td class="table_menu" colspan="4" align="center">택배사 보기</td>
		  </td>
		</tr>
		<tr>
		  <td class="table_body_menu">코드<font color=#CC3300> *</font></td>
		  <td class="table_body_text" colspan="3">
		  <?=$my_cd?>
		  </td>
		</tr>
		<tr>
		  <td class="table_body_menu" width="20%" cols>택배사명<font color=#CC3300> *</font></td>
		  <td class="table_body_text" colspan="3">
		  <?=$my_nm?>
		  </td>
		</tr>
		<tr>
		  <td class="table_body_menu">링크주소</td>
		  <td class="table_body_text" colspan="3">
		  <?=$my_nm_desc?></td>
	    </tr>
	  </table>
	</td>
  </tr>
</table>

<br>


<table width='<?=$cf_table_wd_large?>' border="0" cellspacing="0" cellpadding="1" >
  <tr>
    <td class="table_line">
	  <table width="<?=$cf_table_wd_small?>" border="0" cellspacing="1" cellpadding="3">
	    <tr>
		  <td align="center" colspan="2" class="table_body_menu">
			<?=$MODIFY?> <?=$DELETE?> <?=$LIST?>
		  </td>
	    </tr>
	  </table>
    </td>
  </tr>
</table>

