<table width="<?=$cf_table_wd_large?>" border="0" cellspacing="0" cellpadding="1" >
  <tr>
    <td class="table_line">
		<table width="<?=$cf_table_wd_small?>" border="0" cellspacing="1" cellpadding="3">
		  <tr>
			<td colspan='2' align='center' class="table_menu"><b>회원정보 삭제</b></td> 
		  </tr>

		  <tr height='30'>
			<td width="20%" class="table_body_menu">&nbsp;&nbsp;&nbsp;&nbsp;<img src="<?=$cf_images_dir?>/icon_ring2.gif"> 성 명</td>
			<td class="table_body_text" width="80%">&nbsp;&nbsp;<?=$my_cm_nm?></td>
		  </tr>

		  <tr height='30'>
			<td class="table_body_menu">&nbsp;&nbsp;&nbsp;&nbsp;<img src="<?=$cf_images_dir?>/icon_ring2.gif"> 아이디</td>
			<td class="table_body_text">&nbsp;&nbsp;<?=$my_cm_id?></td>
		  </tr>

		  <!-- <tr height='30'>
			<td  class="table_body_menu">&nbsp;&nbsp;&nbsp;&nbsp;<img src="<?=$cf_images_dir?>/icon_ring2.gif"> 패스워드문</td>
			<td class="table_body_text">&nbsp;&nbsp;<?=$my_cm_passwd_q_nm?></td>
		  </tr>

		  <tr height='30'>
			<td  class="table_body_menu">&nbsp;&nbsp;&nbsp;&nbsp;<img src="<?=$cf_images_dir?>/icon_ring2.gif"> 패스워드답</td>
			<td class="table_body_text">&nbsp;&nbsp;<?=$my_cm_passwd_a?></td>
		  </tr> -->


		  <tr height='30'>
			<td class="table_body_menu">&nbsp;&nbsp;&nbsp;&nbsp;<img src="<?=$cf_images_dir?>/icon_ring2.gif"> 전화번호</td>
			<td class="table_body_text">&nbsp;&nbsp;<?=$my_cm_tel?></td>
		  </tr>

		  <tr height='30'>
			<td class="table_body_menu">&nbsp;&nbsp;&nbsp;&nbsp;<img src="<?=$cf_images_dir?>/icon_ring2.gif"> E-Mail</td>
			<td class="table_body_text">&nbsp;&nbsp;<?=$my_cm_email?></td>
		  </tr>

		  <tr height='30'>
			<td class="table_body_menu">&nbsp;&nbsp;&nbsp;&nbsp;<img src="<?=$cf_images_dir?>/icon_ring2.gif"> 메일수신 여부	</td>
			<td class="table_body_text">&nbsp;&nbsp;<?=$my_cm_email_yn?></td>
		  </tr>
		  
		  <tr height='30'>
			<td class="table_body_menu">&nbsp;&nbsp;&nbsp;&nbsp;<img src="<?=$cf_images_dir?>/icon_ring2.gif">휴대폰 번호</td>
			<td class="table_body_text">&nbsp;&nbsp;<?=$my_cm_hp?></td>
		  </tr>

		  <tr height='30'>
			<td class="table_body_menu">&nbsp;&nbsp;&nbsp;&nbsp;<img src="<?=$cf_images_dir?>/icon_ring2.gif"> 현재레벨</td>
			<td class="table_body_text">&nbsp;&nbsp;<?=$my_cm_level_nm?></td>
		  </tr>

		  <!-- <tr height='30'>
			<td class="table_body_menu">&nbsp;&nbsp;&nbsp;&nbsp;<img src="<?=$cf_images_dir?>/icon_ring2.gif"> 요청레벨</td>
			<td class="table_body_text">&nbsp;&nbsp;<?=$my_cm_req_level_nm?></td>
		  </tr> -->

		  <tr height='70'>
			<td class="table_body_menu">&nbsp;&nbsp;&nbsp;&nbsp;자기 소개	</td>
			<td class="table_body_text">&nbsp;&nbsp;<?=$my_cm_etc?></td>
		  </tr>
		</table>
	  </td>
	</tr>
</table>


<br>
<table width="<?=$cf_table_wd_large?>" border="0" cellspacing="0" cellpadding="0" >
  <tr>
	<td background='<?=$cf_images_dir?>/box_bg.gif' width='20'><img src="<?=$cf_images_dir?>/box_top.gif"></td>
	<td background='<?=$cf_images_dir?>/box_bg.gif' align='right'><?=$LIST?> <?=$DELETE?> <?=$CANCEL?></td>
	<td background='<?=$cf_images_dir?>/box_bg.gif' width='20' align='right'><img src="<?=$cf_images_dir?>/box_end.gif"></td>
  </tr>
</table>
<BR>
<BR>
