<ul>
  <?if($cf_cook_level == "aa") {?>
    <li><a href="/manager/code/list.html?a_gb=code&a_cd=1&a_item=0">종합코드관리</a></li>
    <li><a href="/manager/table/list.html?a_gb=admin&a_cd=1&a_item=0">프로그램관리</a></li>
  <?}?>
    <li><a href="/manager/member/list.html?a_gb=member&a_cd=3&a_item=0">회원관리</a></li>
    <li><a href="/manager/stats/list.html?a_gb=board&a_cd=27&a_item=0">통계관리</a></li>
	<li><a href="/manager/counter/list.html?a_gb=counter&a_cd=1&a_item=0">방문자</a></li>

    <li><a href="/manager/shop/list.html?a_gb=shop&a_cd=1&a_item=0">상품관리</a></li>
    <li><a href="/manager/order/list.html?a_gb=order&a_cd=1&a_item=0">상품주문관리</a></li>
	<!-- <li><a href="/manager/route/list.html?a_gb=admin&a_cd=8&a_item=0">가입경로</a></li> -->
</ul>