<br>
<style>
.3456title {
	width: <?=$cf_table_wd_large?>;
	padding: 5px;
	border: 1px solid #ccc;
	background: #fff;
	font-size: 12px;
	line-height: 19px;
	font-weight: bold;
	margin: 0 10px 4px 10px;
	color: #6a6;
	text-align:left;
}

.3456title ul {
	margin: 0;
	padding: 5 10 5 0;
}

.3456title ul li {
	margin: 0; 
	padding: 0;
}
</style>
<?
	if ($a_gb == "board" && $a_cd == "17" && $a_item == "0")
	{
?>
<table width="564" cellpadding="0" cellspacing="0" border="0">
  <tr>
    <td><img src="/images/box2_top.gif"></td>
  </tr>
  <tr>
    <td background="/images/box2_bg.gif" align="center">
      <table width="90%" cellpadding="0" cellspacing="2" border="0"> 
        <tr>
          <td width="10"><img src="/images/box2_icon.gif"></td>
          <td>누구나 자유롭게 궁금하신 점을 질문하실 수 있습니다.</td>
        </tr>
        <tr>
          <td width="10"><img src="/images/box2_icon.gif"></td>
          <td>Q&A와 무관하거나 공서양속에 반하는 글은 통보없이 삭제됩니다.</td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td><img src="/images/box2_footer.gif"></td>
  </tr>
</table>

<?
	}
	else if ($a_gb == "board" && $a_cd == "18" && $a_item == "0")
	{
?>
<table width="564" cellpadding="0" cellspacing="0" border="0">
  <tr>
    <td><img src="/images/box2_top.gif"></td>
  </tr>
  <tr>
    <td background="/images/box2_bg.gif" align="center">
      <table width="90%" cellpadding="0" cellspacing="2" border="0"> 
        <tr>
          <td width="10"><img src="/images/box2_icon.gif"></td>
          <td>LIFEZONE 회원이면 누구나 자유롭게 질문 및 덧글을 작성하실 수 있습니다.</td>
        </tr>
        <tr>
          <td width="10"><img src="/images/box2_icon.gif"></td>
          <td>쇼핑몰 운영 목적에서 벗어나거나 공서양속에 반하는 글은 통보없이 삭제됩니다</td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td><img src="/images/box2_footer.gif"></td>
  </tr>
</table>
<?
	}
?>
</center>
