<?php

try {
	require_once dirname(__FILE__).DIRECTORY_SEPARATOR.'setting.php';
	

	$database_record = "$2a$10$..."; // generated by devise
	$user_input = 'asdasd';
	$password = crypt($user_input, '$2a$10$usesomesillystringforsalt$');

	if (crypt($user_input, $database_record) == $password) {
		echo "<br/>Password verified!";
	} else {
   echo '<br/>failed!';
	}

	$con=null;

	if ($clean['return_url']) {
		$sl_redirect=$clean['return_url'];
	} else {
		$sl_redirect='/index.php';
	}

	require_once INCLUDE_DIRECTORY . DIRECTORY_SEPARATOR . 'success.php';
} catch(Exception $e) {
	$con=null;

	require_once INCLUDE_DIRECTORY . DIRECTORY_SEPARATOR . 'error.php';
}

?>